Cookies
Strandol/code-and-magick pull request #1
Opened 2016-11-22 23:33 UTC by Strandol

2016-11-22 23:34 UTC, Strandol commented
/cc DudaGod Come to watch

2016-11-23 22:07 UTC, DudaGod commented on build/js/form.js
> +  };
это вынеси в отдельный файл

2016-11-23 22:11 UTC, DudaGod commented on build/js/form.js
> +  var birthday = new Date(1997, 12, 23);
Нужно вверх вынести как константу и объявить как константу (большими буквами). Например MY_BIRTHDAY

2016-11-23 22:11 UTC, DudaGod commented on build/js/form.js
> +  form.onsubmit = function (evt) {
пиши e или event целиком.
Опять пробел между function и скобками

2016-11-23 22:18 UTC, DudaGod requested changes

2016-11-23 22:18 UTC, DudaGod commented on build/js/form.js
> +  formName.oninput = function (evt) {
пробел опять же и evt может переименуем в `e` или `event`?

2016-11-23 22:18 UTC, DudaGod commented on build/js/form.js
> +    }
не чувствуешь что у тебя тут код дублируется с тем что ниже для `formReview`?
По хорошему его нужно вынести в отдельную функцию.

2016-11-23 22:18 UTC, DudaGod commented on package.json
> +    "url": "git+ssh://git@github.com/htmlacademy-javascript/35690-code-and-magick.git"
url не твой

2016-11-23 22:18 UTC, DudaGod commented on package.json
> +  "name": "dvalian",
что это за название такое?

2016-11-23 22:18 UTC, DudaGod commented on package.json
>    "author": "Илья Коваленко",
Коленко =)

2016-11-23 23:43 UTC, Strandol commented
@DudaGod Исправил

2016-11-26 16:13 UTC, DudaGod requested changes

2016-11-26 16:13 UTC, DudaGod commented on package.json
> +  }
по царски исправил.
Запятую верни.

2016-11-26 16:13 UTC, DudaGod commented on package.json
>    "engines": {
и тут тогда сразу ошибки не будет

2016-11-26 16:13 UTC, DudaGod commented on build/js/form.js
>  (function() {
понимаешь почему здесь функция так объявлена?

2016-11-26 16:13 UTC, DudaGod commented on build/js/form.js
> +  var formName = document.querySelector('#review-name');
плохая практика искать элемент по id. У тебя же есть класс - `review-form-field-name`.
Так найди его вот так:
```js
var formName = form.querySelector('.review-form-field-name');
```

То есть не обязательно через `document` - искать. Мой вариант быстрее работать будет )

2016-11-26 16:13 UTC, DudaGod commented on build/js/form.js
> +  var formName = document.querySelector('#review-name');
И давай эту переменную назовем `reviewerName`. Из нее сразу будет понятно, что это имя ревьювера. Сейчас из названия получается, что это имя формы - `formName`.

А за счет того, что мы будем ее инициализировать вот так:
```js
var reviewerName = form.querySelector('.review-form-field-name');
```
будет сразу понятно что она находится внутри формы.

2016-11-26 16:13 UTC, DudaGod commented on build/js/form.js
> +  var formReview = document.querySelector('#review-text');
Может `reviewerComment` назовем и будем искать по классу, а не по id и внутри формы, а не внутри всего `document`

2016-11-26 16:13 UTC, DudaGod commented on build/js/form.js
> +  var formNameLabel = document.querySelector('.review-fields-name');
что то не нравится мне название этой переменной.
Я должен сразу понять, что это. Сейчас это "имя метки формы", нехрена не ясно. По сути, это поле с информацией о том какой элемент формы еще не заполнен.
Предлагаю так - `requiredFieldReviewerName`.
Есть предложения получше?

2016-11-26 16:13 UTC, DudaGod commented on build/js/form.js
> +  var formNameLabel = document.querySelector('.review-fields-name');
да и ищи этот класс внутри формы, а не в `document`

2016-11-26 16:13 UTC, DudaGod commented on build/js/form.js
> +  var formReviewLabel = document.querySelector('.review-fields-text');
Здесь тоже давай красивее назовем и будем искать в форме.

2016-11-26 16:13 UTC, DudaGod commented on build/js/form.js
> +  CheckCookie(formName);
это функция, а не класс. Поэтому вызов должен быть с маленькой буквы, как и объявление функции

2016-11-26 16:13 UTC, DudaGod commented on build/js/cookies.js
> +var docCookies = {
ты понимаешь почему сможешь использовать эту переменную во втором файле form.js?
Хотя ты ее никак во втором файле не реквайришь и из этого файла эту переменную не возвращаешь.

Напиши ответ на этот вопрос тут в комменты

2016-11-26 16:13 UTC, DudaGod commented on build/js/form.js
> +  CheckCookie(formReview);
Давай 2 этих вызова функций унесем в отдельную функцию.

Например можно объявить функцию которая будет принимать массив кук - которые нужно проверить, установлены они или нет.
```js
function checkCookies(cookies) {
  // тут пробегаешься по массиву и для каждого из них проверяешь куку  и выставляешь значение
}
```

2016-11-26 16:13 UTC, DudaGod commented on build/js/form.js
> +  formOpenButton.onclick = function(event) {
а для всех эти обработчиков событий тоже предлагаю создать отдельную функцию, например `initEventsHandlers`

В которой будут установлены все эти обработчики для элементов форм.

2016-11-26 16:13 UTC, DudaGod commented on build/js/form.js
> +    event.preventDefault();
а зачем ты тут `preventDefault` юзаешь?

2016-11-26 16:13 UTC, DudaGod commented on build/js/form.js
> +  formName.oninput = function (event) {
пробел

2016-11-26 16:13 UTC, DudaGod commented on build/js/form.js
> +    event.preventDefault();
а нафига ты это везде добавляешь?

2016-11-26 16:13 UTC, DudaGod commented on build/js/form.js
> +  function CheckCookie(formElement) {
давай эту функцию назовем - `isCookieSetFor(formElement)`

2016-11-26 16:13 UTC, DudaGod commented on build/js/form.js
> +    event.preventDefault();
и тут не понял, для чего?

2016-11-26 16:13 UTC, DudaGod commented on build/js/form.js
> +  formName.oninput = function (event) {
и почему ты тут oninput используешь, а не onchange?

2016-11-26 16:13 UTC, DudaGod commented on build/js/form.js
> +  formReview.oninput = function (event) {
Здесь тоже. Почему oninput используешь, а не onchange?

2016-11-26 16:13 UTC, DudaGod commented on build/js/form.js
> +  function CheckValue(formElement, elementLabel) {
Эте функция, а не класс - поэтому с маленькой буквы должен называться.
Дальше мне не нравится название. Из него не понятно, что эта функция делает.
Судя по названию проверяет значение, но на самом деле оно его устанавливает. Т.е. добавляет класс к элементу или удаляет его.

Давай его назовем `changeStateRequiredField`? А принимать она будет `fieldValue` и сам эелемент у которого класс менять будет

2016-11-26 16:13 UTC, DudaGod commented on build/js/form.js
> +    formElement.value === '' ? elementLabel.classList.remove('invisible') : elementLabel.classList.add('invisible');
тут тернарник лучше в три строки писать:
```js
value
  ? res1
  : res2;
```

2016-11-26 16:13 UTC, DudaGod commented on build/js/form.js
> +    event.preventDefault();
ты его везде фигачишь что ли? )

2016-11-26 16:13 UTC, DudaGod commented on build/js/form.js
> +    docCookies.setItem(formName.name, formName.value, new Date(Date.now() + (Date.now() - MY_BIRTHDAY.getTime())));
давай расчет кол-ва дней с момента твоего рождения по сейчас унесем в понятно читаемую функцию?

2016-11-26 16:13 UTC, DudaGod commented on build/js/form.js
> +    this.submit();
Чему тут this равен?
И что значит этот вызов, что он выполнит?

2016-11-26 22:35 UTC, illiakovalenko commented on build/js/form.js
>  (function() {
@DudaGod Да, это как отдельный закрытый модуль

2016-11-26 22:54 UTC, Strandol commented on build/js/form.js
> +    this.submit();
@DudaGod Отошлет форму

2016-11-26 22:55 UTC, Strandol commented on build/js/cookies.js
> +var docCookies = {
@DudaGod Я же подключил ее в index.html, а это глобальная переменная, которая доступна везде

2016-11-26 23:34 UTC, Strandol commented on build/js/form.js
> +  formReview.oninput = function (event) {
@DudaGod onchange изменяет после нажатия в другую область, а oninput сразу при вводе

2016-11-27 15:26 UTC, DudaGod commented on build/js/form.js
> +      this.submit();
ты не ответил, чему тут this равен?
И почему ты его тут юзаешь?

2016-11-27 15:30 UTC, DudaGod commented on build/js/form.js
> +      formContainer.classList.remove('invisible');
ты кстати про `eventPreventDefault` ничего не написал. Почему его юзал и почему удалил?

2016-11-27 15:45 UTC, DudaGod commented on build/js/form.js
> +      reviewerComment.value = docCookies.getItem(reviewerComment.name);
ты тут дублирования не замечаешь? Я же для этого и предлагал передавать массив элементов сюда.

Представь, что тебе так нужно проверить 20 полей и всем им значения из кук установить.
Так у тебя будет 40 строк кода на это. А при передаче массивом в этом месте код не изменится

2016-11-27 15:46 UTC, DudaGod commented on build/js/form.js
> +      reviewerComment.value = docCookies.getItem(reviewerComment.name);
Да и без фигурных скобочек if-ы плохо писать.

2016-11-27 15:50 UTC, DudaGod commented on build/js/form.js
> +  isCookieSetFor(docCookies);
тебе тут все нравится?
Получается мы зовем функцию которая из ее названия должна вернуть boolean. И принимает она глобальный объект, который итак видим внутри функции.

Давай подумаем, что тут происходит? Мы проверяем установлена ли кука и если да, то меняем значение поля. Я предлагаю тут ее назвать `initFieldValues`. Т.е. инициализируем значения полей. Которая будет принимать массив элементов и внутри себя проверять есть ли кука для элемента и если есть инициализировать.

Чтобы сильно не упарываться в названия предлагаю так фигануть:
```js
function initFieldValues(elems) {
  elems.forEach(function(elem) {
     if(docCookies.hasItem(elem.name)) {
       elem.value = docCookies.getItem(elem.name);
    }
  })
}
```

Так разве не красивее будет и понятнее?

2016-11-27 15:51 UTC, DudaGod commented on build/js/form.js
> +  isCookieSetFor(docCookies);
А вызывать ее будешь так:
```js
initFieldValus([reviewerName, reviewerComment]);
```

2016-11-27 15:56 UTC, DudaGod commented on build/js/form.js
> +    reviewerName.oninput = function () {
еще раз хочу поговорить про `oninput` и `onchange`.
oninput - будет тригерится каждый божий раз когда я ввожу по символу.
Т.е. если я введу "Дима" - то функция `changeStateRequiredField` - вызовется 4 раза. А разве мы хотим ее столько раз вызывать?
А onchange - стригерится в конце ввода (когда фокус перейдет), т.е. если введу "Дима" - т функция вызовется 1 раз.

2016-11-27 15:57 UTC, DudaGod commented on build/js/form.js
> +      changeStateRequiredField(requiredFieldReviewerName.value, requiredFieldReviewerComment);
кажется ты тут не тот `value` передал

2016-11-27 22:13 UTC, closed without merging