Module3 task1
Strandol/code-and-magick pull request #11
Opened 2016-11-30 23:07 UTC by Strandol

2016-11-30 23:09 UTC, Strandol commented
@DudaGod I am ready

2016-12-03 23:23 UTC, DudaGod requested changes

2016-12-03 23:23 UTC, DudaGod commented on js/reviews.js
> +  var reviews;
тебе не кажется, что эта переменная тут не очень смотрится?

Ее нужно ниже опустить, а тут оставить только те, что получают значения сразу

2016-12-03 23:23 UTC, DudaGod commented on js/reviews.js
> +  var ReadyState = {
давай это назовем `XHR_STATE` - т.к. это по идеи будет константным значением, которое ты менять не будешь по коду

2016-12-03 23:23 UTC, DudaGod commented on js/reviews.js
> +  var REQUEST_FAILURE_TIMEOUT = 8000;
почему 8000?

2016-12-03 23:23 UTC, DudaGod commented on js/reviews.js
> +  var reviews;
И зачем ты `reviews` определяешь тут, а не в том месте где ее нужно использовать?

2016-12-03 23:23 UTC, DudaGod commented on js/reviews.js
> +  var reviewsBlock = document.querySelector('.reviews');
что то мне `reviewsBlock` не очень нравится. Кажется, что это должно быть `reviewsList`, но он выше использован, возможно верхний можно во что то получше переименовать?

2016-12-03 23:23 UTC, DudaGod commented on js/reviews.js
> +    setupFilters();
почему само объявление функции почти в самом конце файла? Было бы правильнее ее поставить сразу после этой функции (т.е. после `loadReviewsList`)

2016-12-03 23:23 UTC, DudaGod commented on js/reviews.js
> +  function setupFilters(){
пробел где?

2016-12-03 23:23 UTC, DudaGod commented on js/reviews.js
> +  function setupFilters(){
И эту функцию правильнее было бы назвать initFilters, а не setup

2016-12-03 23:23 UTC, DudaGod commented on js/reviews.js
> +    var filters = reviewsFilter.querySelectorAll('.reviews-filter-item');
почему сразу не сделаешь из нее массив, чтобы можно было юзать так:
```js
filters.forEach(...);
```

У тебя сейчас `filters` - это ArrayLike (т.е. не совсем массив) его нужно привести к нему с помощью slice.

2016-12-03 23:23 UTC, DudaGod commented on js/reviews.js
> +    for(var i = 0; i < filters.length; i++){
пробел после скобки - )

2016-12-03 23:23 UTC, DudaGod commented on js/reviews.js
> +        setupFilter(activeFilter.htmlFor);
htmlFor - это что тут?
Объявление функции `setupFilter` должно быть ниже его места использования. В данном случаче так же легче читать код будет.

2016-12-04 15:49 UTC, DudaGod requested changes
Первый пункт задания ты проскипал походу:
"1. Отключите загрузку данных из файла data/reviews.js убрав подключение этого скрипта из index.html."

2016-12-04 15:49 UTC, DudaGod commented on js/reviews.js
> +    setupFilters();
Так удобнее читается, то есть последовательно, как книжка или история небольшая

2016-12-04 15:49 UTC, DudaGod commented on js/reviews.js
> +  function setupFilter(filter) {
эта функция должно быть ниже `setupFilters` - и по названию не понятно, что она делает.
Кажется, что правильнее ее назвать как то так - `setActiveFilter`. То есть прежде чем назвать функцию или переменную подумай, что в ней происходит и за что она отвечает это поможет найти правильное название.

2016-12-04 15:49 UTC, DudaGod commented on js/reviews.js
> +        setupFilter(activeFilter.htmlFor);
Попробуй .value вместо .htmlFor

2016-12-04 15:49 UTC, DudaGod commented on js/reviews.js
> +  function refreshReviews(reviews) {
Давай назовем ее `renderReviews`, а не refresh.

2016-12-04 15:49 UTC, DudaGod commented on js/reviews.js
> +      switch (loadedXhr.readyState){
пустую строку вставь между объявлением переменной и switch, так же легче читать будет

2016-12-04 15:49 UTC, DudaGod commented on js/reviews.js
> +        case ReadyState.LOADING:
нафига ты их тут все перечисляешь их же легче в default обработать, т.е. те варианты которые явно не указаны

2016-12-04 15:49 UTC, DudaGod commented on js/reviews.js
> +        case ReadyState.DONE:
зачем? Он в default итак попадет, так как ты его выше не указал

2016-12-04 15:49 UTC, DudaGod commented on js/reviews.js
> +      switch (loadedXhr.readyState){
и пробел опять провтыкал. Тебе линтер не подсказывает что ли?

2016-12-04 15:49 UTC, DudaGod commented on js/reviews.js
> +      }
дофига строк кода получилось, вот так намного проще будет и понятнее что происходит:
```js
switch (loadedXhr.readyState) {
  case ReadyState.DONE:
    if (loadedXhr.status !== 200) {
      showLoadFailure();
    } else {
      var reviewsData = loadedXhr.response;
      reviewsBlock.classList.remove('reviews-list-loading');
      loadData(JSON.parse(reviewsData));
    }
    break;

  default:
    reviewsBlock.classList.add('reviews-list-loading');
    break;
}
```

2016-12-04 15:49 UTC, DudaGod commented on js/reviews.js
> +          if (loadedXhr.status == 200){
сравнение строгое!!!

2016-12-04 15:49 UTC, DudaGod commented on js/reviews.js
> +    xhr.send();
этот `send` нужно вызывать после подписки на `onreadystatechange` и `ontimeout`

2016-12-04 15:49 UTC, DudaGod commented on js/reviews.js
> +    function loadData(loadedReviews) {
зачем ты тут внутри эту функцию объявляешь?
Объяви ее снаружи и передай в `loadReviews` первым аргументом, который можешь назвать `callback` например.

2016-12-04 15:49 UTC, DudaGod commented on js/reviews.js
> +    xhr.open('get', 'data/reviews.json');
давай путь к файлу объявим вначале как константу

2016-12-04 15:49 UTC, DudaGod commented on js/reviews.js
> +          if(rev1.date < rev2.date){
ты в курсе, что у тебя в `date` обычный строки. Типа такого - "2014-01-11". Как они по твоему правильно рассортируются в твоем случае? Отсюда вопрос: ты проверял свой код на работоспособность?

Эти даты нужно приводить к new Date

2016-12-04 15:49 UTC, DudaGod commented on js/reviews.js
> +        filterReviews.sort(function (rev1, rev2) {
так ты же можешь использовать чейнинг:
```js
filterReviews = filterReviews.filter(function() {})
  .sort(funciton() {})
  .map(function() {})
  ....
```

2016-12-04 15:49 UTC, DudaGod commented on js/reviews.js
> +          if(rev1.date < rev2.date){
Ты заметил, что у тебя в этой большой функции часто повторяется очень похожий sort?
Может стоит вынести его в отдельную функцию `compareElements`?

И ты как то сложно проверяешь. Тут достаточно:
```js
filterReviews.sort(function (rev1, rev2) {
  return rev1.date - rev2.date;
```

Подумай почему мой вариант будет работать.

2016-12-04 15:49 UTC, DudaGod commented on js/reviews.js
> +          if(rev1['review-rating'] < rev2['review-rating']){
опять ты эти квадратные скобочки лепишь и не ставишь пробелы.

2016-12-04 15:49 UTC, DudaGod commented on js/reviews.js
> +  function getFilteredReviews(reviews, filter) {
эта функция ярость господня.

2016-12-05 11:05 UTC, Strandol commented on js/reviews.js
> +        setupFilter(activeFilter.htmlFor);
@DudaGod Оставил .htmlFor потому что это я беру label, а у input классов нету

2016-12-05 11:15 UTC, Strandol commented on js/reviews.js
> +      switch (loadedXhr.readyState){
@DudaGod Неа, не подсказывает

2016-12-05 11:16 UTC, Strandol commented on js/reviews.js
> +        case ReadyState.LOADING:
@DudaGod Делал как на лекции, нагляднее

2016-12-05 11:41 UTC, Strandol commented on js/reviews.js
> +          if(rev1.date < rev2.date){
@DudaGod потому что, если меньше 0 то будет перестановка, если 0- то ничего не поменяется , если больше 0, то обратная замена

2016-12-05 11:59 UTC, Strandol commented on js/reviews.js
> +        filterReviews.sort(function (rev1, rev2) {
@DudaGod Не шарю еще

2016-12-05 12:00 UTC, Strandol commented on js/reviews.js
> +        filterReviews.sort(function (rev1, rev2) {
хотя понял, можно

2016-12-05 20:32 UTC, DudaGod requested changes

2016-12-05 20:32 UTC, DudaGod commented on js/reviews.js
>    loadReviewsList();
чего вызов основной функции с которой начинает все вертется прилепил к объявлению переменной. Дай им воздух!!!

2016-12-05 20:32 UTC, DudaGod commented on js/reviews.js
> +    filters.forEach(function(filter) {
Илья, так работать не будет. Ты видимо не проверил, после исправлений.
У тебя сейчас `filters` - ArrayLike, у него нет метода .forEach

2016-12-05 20:32 UTC, DudaGod commented on js/reviews.js
> +    var filters = reviewsFilter.querySelectorAll('.reviews-filter-item');
раздели пустой строкой объявление и вызов `forEach`

2016-12-05 20:32 UTC, DudaGod commented on js/reviews.js
> +    var pathToJSON = 'data/reviews.json';
ну и чего ты ее тут объявил?
Уноси в начало модуля, туда где у тебя `REQUEST_FAILURE_TIMEOUT` объявлен.
И назови как нибудь покруче. Вдруг у тебя завтра файлы не в json формате будут. Назвать нужно более абстрактно. Например - `REVIEWS_DATA_PATH` или еще круче =)

2016-12-05 20:32 UTC, DudaGod commented on js/reviews.js
> +
лишняя пустая строка

2016-12-05 20:32 UTC, DudaGod commented on js/reviews.js
> +    renderReviews(loadedReviews)
точка с запятой

2016-12-05 20:32 UTC, DudaGod commented on js/reviews.js
> +        .sort(function (rev1, rev2) {
у тебя здесь и ниже повторяется одна и таже функция. Сделай нормальную функцию `compareElements` вместо `compareDates`.

2016-12-05 20:32 UTC, DudaGod commented on js/reviews.js
> +  function compareDates(filterReviews) {
ты в эту функцию должен был унести callback, который передаешь аргументом в `sort`.
А ты вынес больше чем нужно.
И в эту функцию ты должен просто передавать два элемента и фигачить разницу между ними.

2016-12-05 20:32 UTC, DudaGod commented on js/reviews.js
> +      return new Date(rev2.date).getTime() - new Date(rev1.date).getTime();
т.е. приведние к датам должно быть не в этой функции, а до ее вызова.
Или так:
```js
reviews.sort(compareElements(value1, value2)) {
  return value1 - value2;
}
```

2016-12-05 20:32 UTC, DudaGod commented on js/reviews.js
> +        compareDates(filterReviews);
а тут ты можешь прежде чем вызывать `sort`, пройтись по массиву с помощью map или reduce и в каждом заменить `date` на `new Date(date)`, но при этом чтобы остальные поля остались не изменными

2016-12-05 21:25 UTC, DudaGod requested changes

2016-12-05 21:25 UTC, DudaGod commented on js/reviews.js
> +  function compareDates(filterReviews) {
```js
function compareElements(elem1, elem2) {
  return elem1 - elem2;
}
```

2016-12-05 21:25 UTC, DudaGod commented on js/reviews.js
> +        compareDates(filterReviews);
filterReviews.sort(function(review1, review2) {
  var date1 = new Date(review1);
  var date2 = new Date(review2);
  return compareElements(date1, date2);
});

2016-12-05 21:25 UTC, DudaGod commented on js/reviews.js
> +        .sort(function (rev1, rev2) {
.sort(function(review1, review2) {
  return compareElements(review2.rating, review1.rating);
});

2016-12-06 09:00 UTC, merged