Events
Strandol/code-and-magick pull request #13
Opened 2016-12-06 19:22 UTC by Strandol

2016-12-17 20:15 UTC, DudaGod requested changes

2016-12-17 20:15 UTC, DudaGod commented on js/gallery.js
> +        if(event.target.parentNode.classList.contains('photogallery-image')) {
Пробела нет после if-а

2016-12-17 20:15 UTC, DudaGod commented on js/gallery.js
> +}());
пустой строки нет в конце файла!!!

2016-12-17 20:15 UTC, DudaGod commented on js/game_demo.js
> +    var hideEvent = new Event('hide');
Тут нужно использовать CustomEvent. Так как это не встроенное событие в  js. Вот тут почитай - https://learn.javascript.ru/dispatch-events#свои-события

2016-12-17 20:15 UTC, DudaGod commented on js/game_demo.js
> +        return true;
Илья подумай как здесь можно сделать красивее.

2016-12-17 20:15 UTC, DudaGod commented on js/game_demo.js
> +    clouds.addEventListener('hide', function () {
что это за пробел между function и скобками?

2016-12-17 20:15 UTC, DudaGod commented on js/game_demo.js
> +        if (clouds.getBoundingClientRect().top < -clouds.offsetHeight) {
а вот так нельзя переписать:
```js
clouds.getBoundingClientRect().bottom < 0
```

2016-12-17 20:15 UTC, DudaGod commented on js/game_demo.js
> +    var visibility = true;
а зачем ты `cloudsTimeout` и `visibility` тут определил? Ты же их используешь только в одной функции. Там и объявляй.

2016-12-17 20:15 UTC, DudaGod commented on js/game_demo.js
> +    var visibility = true;
И что еще за `cloudsTimeout`? Таймаут облаков? )
Просто объяви ее как `timerId`

2016-12-17 20:15 UTC, DudaGod commented on js/game_demo.js
> +    var visibility = true;
тоже самое с visibility. Видимость чего? Хрен пойми, если я хочу понять, то мне нужно идти в код штырить.
Назови его лучше - isCloudsVisible. То есть сразу понятно что эта переменная принимает булеан значения

2016-12-17 20:15 UTC, DudaGod commented on js/game_demo.js
> +    });
И я что-то я не понял смысла такой функции. Ты же так же само можешь написать функцию обычную, которая будет просто определять вышли облака за границы или нет. И ни на что подписываться не нужно

2016-12-17 20:15 UTC, DudaGod commented on js/game_demo.js
> +            clouds.style.backgroundPosition = (clouds.getBoundingClientRect().top - clouds.offsetWidth*2 - document.documentElement.clientWidth) + 'px 0px';
кровь из глаз =)
Подумай как можно красивее тут написать.

2016-12-17 20:15 UTC, DudaGod commented on js/game_demo.js
> +        if (visibility != false) {
опять забыл про строгое равенство - !==
И не понятно значем тебе проверять, что не false. Если это все равно что написать:
```js
if (visibility) {}
```

2016-12-17 20:15 UTC, DudaGod commented on js/game_demo.js
> +    });
"испускает кастомное событие «исчезновения блока с облаками» из поля зрения"

Ты тут не true / false должен возвращать. А двигать облачка.

2016-12-17 20:15 UTC, DudaGod commented on js/game_demo.js
> +            clouds.style.backgroundPosition = (clouds.getBoundingClientRect().top - clouds.offsetWidth*2 - document.documentElement.clientWidth) + 'px 0px';
и это должно переехать в кастомное событие хайд

2016-12-17 20:15 UTC, DudaGod commented on js/game_demo.js
> +}());
"Добавьте обработчик события, отключающий параллакс, реагирующий на событие «исчезновения блока с облаками» из поля зрения."

Не вижу где у тебя доп. событие на это задание?

2016-12-17 20:15 UTC, DudaGod commented on js/game_demo.js
> +        clearTimeout(cloudsTimeout);
не понял, а зачем ты это до `setTimeout` вызываешь?

2016-12-17 20:15 UTC, DudaGod commented on js/gallery.js
> +        if(event.target.parentNode.classList.contains('photogallery-image')) {
Не правильно тут написано.
допустим у тебя такой html:
```html
<div class="main">
  <div class="child">
    <a class="link">click on me</a>
  </div>
</div>
```

Получается ты допустим вешаешь обработчик клика по блоку main. У тебя срабатывает клик на ссылке - 'link'. У тебя код идет смотрит класс родителя - это будет "child". А ты проверяешь на main. И в итоге твой код скажет нефига клика не было. Ты понял о чем я? Попоробуй написать правильно.

2016-12-17 20:15 UTC, DudaGod commented on js/gallery.js
> +            setCloseBtnEnabled();
что то название функции вообще не очень.
Установить кнопку закрытия включенным? Так это переводится? )
В этой функции у тебя же обработчик события.

`setCloseBtnHandler` - кажется лучше звучит

2016-12-17 20:15 UTC, DudaGod commented on js/gallery.js
> +            galleryOverlay.classList.remove('invisible');
может в функцию унести с названием - `showGalleryOverlay`?

2016-12-17 20:15 UTC, DudaGod commented on js/gallery.js
> +            keyHandler();
`setKeyHandlers` ?

2016-12-17 20:15 UTC, DudaGod commented on js/gallery.js
> +    function keyPress(event) {
по `keyPress` нефига не понятно. Это же у тебя функция обработчиком клавишных событий. Так и давай назовем ее `keyHandlers`

2016-12-17 20:15 UTC, DudaGod commented on js/gallery.js
> +                galleryOverlay.classList.add('invisible');
вынесем в функцию `hideGalleryOverlay` ?

2016-12-17 20:15 UTC, DudaGod commented on js/reviews.js
> +                  });
ты видишь что тут не красиво получилось?

Напиши так:
```js
filterReviews = filterReviews
    .filter(function(review) {
        return review.rating >= 3
    })
    .sort(function (rev1, rev2) {
        return compareElements(rev2.rating,rev1.rating);
    });
```

2016-12-17 20:15 UTC, DudaGod commented on js/reviews.js
> +                  });
тут тоже некрасиво

2016-12-17 20:15 UTC, DudaGod commented on js/reviews.js
> +              })
точка с запятой

2016-12-17 20:15 UTC, DudaGod commented on js/reviews.js
> +      }
где default?

2016-12-17 20:15 UTC, DudaGod commented on js/reviews.js
> +      localStorage.setItem('filter',filter);
пробел нигде нехочется вставить? )

2016-12-17 20:15 UTC, DudaGod commented on js/reviews.js
> +      window.addEventListener('scroll', function (event) {
пробела не должно быть между function и скобками

2016-12-17 20:15 UTC, DudaGod commented on js/reviews.js
> +          clearTimeout(scrollTimeout);
опять у тебя какой то скролл таймаут.
Тут же из контекста понятно, что это таймаут для скрола. Так как ты для него обработчик события вешаешь

2016-12-17 20:15 UTC, DudaGod commented on js/reviews.js
> +          clearTimeout(scrollTimeout);
И зачем ты его очищаешь до вызова `setTimeout`?

2016-12-17 20:15 UTC, DudaGod commented on js/reviews.js
> +
зачем тут эта пустая линия?

2016-12-17 20:15 UTC, DudaGod commented on js/reviews.js
> +              if(isBottomReached() && isNextPageAvaliable(filteredReviews, currentPage, PAGE_SIZE)){
после if - пробел
в конце { - тоже должно быть отделено пробелом

2016-12-17 20:15 UTC, DudaGod commented on js/reviews.js
> +              if(isBottomReached() && isNextPageAvaliable(filteredReviews, currentPage, PAGE_SIZE)){
У тебя что линтер не стоит?
`npm run test` - запускай прежде чем пушить )

2016-12-17 20:15 UTC, DudaGod commented on js/reviews.js
> +              if(!isNextPageAvaliable(filteredReviews, currentPage, PAGE_SIZE)){
тоже самое что выше

2016-12-17 23:41 UTC, illiakovalenko commented on js/game_demo.js
> +    var visibility = true;
+

2016-12-18 15:38 UTC, Strandol commented on js/game_demo.js
> +    var hideEvent = new Event('hide');
@DudaGod Встроенное - Для генерации своих, нестандартных, событий, хоть и можно использовать конструктор Event, но существует и специфический конструктор CustomEvent.

2016-12-21 04:56 UTC, DudaGod approved these changes

2016-12-21 04:56 UTC, DudaGod commented on js/gallery.js
> +        event.preventDefault();
обычно после `preventDefault` - пустую строку вставляют

2016-12-21 04:56 UTC, DudaGod commented on js/gallery.js
> +        while(element){
где пробел после скобок? И после while обычно вроде тоже ставят
Линтер не запускал? Или он не ругается на такое сейчас?

2016-12-21 04:56 UTC, DudaGod commented on js/gallery.js
> +        }
а чего ты это все не вынес в отдельную функцию?
Например вот так:
```js
function doesHaveParent(element, className) {
  do {
    if (element.classList.contains('photogallery-image')) {
      return true;
    }
    element = element.parentElement;
  } while (element);
  return false;
}
```

И тут тебя только останется вызывать `doesHaveParent` и если он вернет true, то выполнить все что ты хочешь.

2016-12-21 04:56 UTC, DudaGod commented on js/gallery.js
> +    }
функции слиплись

2016-12-21 04:56 UTC, DudaGod commented on js/gallery.js
> +            galleryOverlay.classList.add('invisible');
чего в функцию не вынес? Я тебе вроде писал про это

2016-12-21 04:56 UTC, DudaGod commented on js/gallery.js
> +            event.preventDefault();
отбей пустой строкой после

2016-12-21 04:56 UTC, DudaGod commented on js/game_demo.js
> +    var moveClouds = new Event('move');
чем тебе `CustomEvent` не подошел? В доке же написано, что лучше его юзать, вместо Event для своих событий.

2016-12-21 04:56 UTC, DudaGod commented on js/game_demo.js
> +    var cloudsPositionX = 0;
у меня опять вопрос. Зачем ты тут инициализируешь `timerId` и `cloudsPositionX`? Они же у тебя используются только в одной функции, там и определи. И объясни зачем ты им нули присваиваешь?

2016-12-21 04:56 UTC, DudaGod commented on js/game_demo.js
> +    clouds.addEventListener('move', move);
кажется тут будет если ты функцию все таки сюда вставишь. Она теперь всего 2 строки и больше нигде не используется.

2016-12-21 04:56 UTC, DudaGod commented on js/game_demo.js
> +        cloudsPositionX = clouds.getBoundingClientRect().top;
Ты уверен, что top - это X? Кажется это Y.
И это не позиция облаков. Это расстояние от верхней точки облаков до верха страницы.

2016-12-21 04:56 UTC, DudaGod commented on js/game_demo.js
> +        clouds.style.backgroundPosition = cloudsPositionX + 'px 0px';
кажется тут будет понятнее если ты просто вставишь - `clouds.getBoundingClientRect().top`

2016-12-21 04:56 UTC, DudaGod commented on js/game_demo.js
> +        clouds.style.backgroundPosition = cloudsPositionX + 'px 0px';
Ты кстати проверил, что это работает?

2016-12-21 04:56 UTC, DudaGod commented on js/game_demo.js
> +        timerId = setTimeout(function() {
вот тут просто пиши:
```js
var timerId = setTimeout(...)
```

2016-12-21 04:56 UTC, DudaGod commented on js/game_demo.js
> +            if(clouds.getBoundingClientRect().bottom < 0) {
пробел после if

2016-12-21 04:56 UTC, DudaGod commented on js/game_demo.js
> +    clouds.addEventListener('move', move);
А ниже увидел, что используется

2016-12-21 04:56 UTC, DudaGod commented on js/game_demo.js
> +            }
Так разве не красивее будет:
```js
clouds.getBoundingClientRect().bottom < 0
  ? clouds.removeEventListener('move', move)
  : clouds.addEventListener('move', move);
```

Если тебе нравится больше твой вариант можешь оставить его.

2016-12-21 04:56 UTC, DudaGod commented on js/reviews.js
> +      'UNSENT' : 0,
а чего ты двоеточие не прибьешь к ключу?

2016-12-21 04:56 UTC, DudaGod commented on js/reviews.js
> +      reviewsFilter.addEventListener('click', function (event) {
лишний пробел после `function`

2016-12-21 04:56 UTC, DudaGod commented on js/reviews.js
> +          if(event.target.classList.contains('reviews-filter-item')){
пробел после if и в конце после скобки

2016-12-21 04:56 UTC, DudaGod commented on npm-debug.log
> +0 info it worked if it ends with ok
это ты зря сюда залил )
Допиши правило в .gitignore

2016-12-21 04:56 UTC, DudaGod commented on js/reviews.js
> +  var timerId;
опять с этим таймером.
Объяви его в месте использования. Тут же он нафиг не нужен никому

2016-12-21 04:56 UTC, DudaGod commented on js/reviews.js
> +      currentPage = 0;
а зачем ты его тут еще раз в ноль устанавливаешь?

2016-12-21 04:56 UTC, DudaGod commented on js/reviews.js
> +          switch (loadedXhr.readyState){
пробел после скобок

2016-12-21 04:56 UTC, DudaGod commented on js/reviews.js
> +      btn.checked = true;
давай объявления переменны вверху напишем, а ниже вызовы всякие. Например так:
```js
reviews = loadedReviews;
var filter = localStorage.getItem('filter') || 'reviews-all';
var btn = document.getElementById(filter);

setActiveFilter(filter);
btn.checked = true;
```

А то ты в одну кучу все запхал и плохо читается.

2016-12-21 04:56 UTC, DudaGod commented on js/reviews.js
> +      reviews.slice(from,to).forEach(function(review) {
пробел после запятой забыл

2016-12-21 04:56 UTC, DudaGod commented on js/reviews.js
> +                      return review.rating >= 3
точка с запятой в конце

2016-12-21 04:56 UTC, DudaGod commented on js/reviews.js
> +                      return review.rating <= 2
точка с запятой в конце

2016-12-21 04:56 UTC, DudaGod commented on js/reviews.js
> +          default: break;
а чего ниже break не напишешь?

2016-12-21 04:56 UTC, DudaGod commented on js/reviews.js
> +          }, 100);
а где очистка таймаута?

2016-12-21 04:57 UTC, DudaGod commented
поправь остатки и в остальном /ok

2016-12-21 10:41 UTC, Strandol commented on js/reviews.js
> +      btn.checked = true;
@DudaGod Не пойдет, потому что у меня фильтр кидается в btn

2016-12-21 10:41 UTC, Strandol commented on js/reviews.js
> +      btn.checked = true;
@DudaGod а, хотя можно.

2016-12-21 12:43 UTC, merged