Reviews
Strandol/code-and-magick pull request #6
Opened 2016-11-28 11:28 UTC by Strandol

2016-11-28 11:28 UTC, Strandol commented
/cc @DudaGod I am ready

2016-11-29 05:25 UTC, DudaGod requested changes

2016-11-29 05:25 UTC, DudaGod commented on js/reviews.js
> +  reviews.forEach(function (review) {
пробел  и тебе не кажется, что forEach слишком большой?

2016-11-29 05:25 UTC, DudaGod commented on js/reviews.js
> +    if(review["author"]["picture"]){
А зачем ты так свойство берешь у объекта? И почему двойные кавычки?

2016-11-29 05:25 UTC, DudaGod commented on js/reviews.js
> +      authorImage.src = review["author"]["picture"];
и тут

2016-11-29 05:25 UTC, DudaGod commented on js/reviews.js
> +      var imageLoadTimeout = setTimeout(function () {
пробел после function

2016-11-29 05:25 UTC, DudaGod commented on js/reviews.js
> +
ты руками этот пробел добавил что ли?

2016-11-29 05:25 UTC, DudaGod commented on js/reviews.js
> +})();
до этого ты скобки вызова функции вроде внутри указывал, а сейчас снаружи

2016-11-29 05:25 UTC, DudaGod commented on js/reviews.js
> +  var reviewsTemplate = document.getElementById('review-template');
там же один template, поэтому правильнее `reviewTemplate` - без s. И объяви ее после `reviewsList`

2016-11-29 05:25 UTC, DudaGod commented on js/reviews.js
> +    var newReview = reviewsTemplate.content.children[0].cloneNode(true);
такая запись на уроке показывалась?

2016-11-29 05:25 UTC, DudaGod commented on js/reviews.js
> +    newReview.querySelector('.review-rating').classList.add(ratingStructure[review['rating']]);
чем тебе `review.rating` - не подошел?

2016-11-29 05:25 UTC, DudaGod commented on js/reviews.js
> +  var reviewsFragment = document.createDocumentFragment();
почему объявление написал ниже предыдыщей строки?

Кажется будет смотрется понятнее если ты их свапнишь.

2016-11-29 05:25 UTC, DudaGod commented on js/reviews.js
> +  reviewsFilter.classList.add('invisible');
давай вынесем это в отдельную функцию, типа как в прошлом модуле

2016-11-29 05:26 UTC, DudaGod commented
Подумай как гигантский `forEach` сделать более понятным и маленьким.

Проверял, что код работает?

2016-11-29 17:32 UTC, Strandol commented on js/reviews.js
> +    var newReview = reviewsTemplate.content.children[0].cloneNode(true);
@DudaGod да, от туда и брал, сказали особо не вдаваться в подробность сейчас,
я так понимаю что берем первого ребенка из reviewsTemplate, и клонируем видимо

2016-11-29 18:14 UTC, Strandol commented
@DudaGod Ready

2016-11-29 21:04 UTC, DudaGod commented on js/reviews.js
>    var reviewsList = document.querySelector('.reviews-list');
почему не поменял очередность?
Не удобно же так читать

2016-11-29 21:05 UTC, Strandol commented on js/reviews.js
>    var reviewsList = document.querySelector('.reviews-list');
@DudaGod  :-1:

2016-11-29 21:05 UTC, Strandol commented on js/reviews.js
>    var reviewsList = document.querySelector('.reviews-list');
@DudaGod Поменяю перед merge

2016-11-29 21:07 UTC, DudaGod commented on js/reviews.js
> +
а для чего тут эта пустая строка?

2016-11-29 21:08 UTC, DudaGod commented on js/reviews.js
>      var oldImage = newReview.querySelector('.review-author');
Не пойму, класс `.review-author` - это типа аватарка?
Если да, то почему она называется `oldImage`? Где new тогда? И почему она должна поменяться?

2016-11-29 21:10 UTC, DudaGod commented on js/reviews.js
> +    if (review.author.picture) {
тебя такой гигансткий if не смущает?
Тут же легко избежать этой лишний вложенности если инвертировать условие.

2016-11-29 21:12 UTC, DudaGod commented on js/reviews.js
>      var oldImage = newReview.querySelector('.review-author');
Кажется я по коду понял, что это не картинка, а место куда загруженная картинка должна встать.
Поэтому некорректно называть эту переменную `oldImage`

2016-11-29 21:12 UTC, DudaGod commented on js/reviews.js
> +  function loadPicture(review, newReview, oldImage) {
и тут тоже, третий аргумент - это не `oldImage`

2016-11-29 21:19 UTC, DudaGod commented on js/reviews.js
>          authorImage.style.backgroundSize = '124px 124px';
так размер указывался в вебинаре или сам где то нашел?

2016-11-29 21:21 UTC, DudaGod commented on js/reviews.js
>        var authorImage = new Image();
может тут просто `avatar` назвать? Кажется так понятнее будет

2016-11-29 21:25 UTC, DudaGod commented
Советую писать через 4 пробела, а не через 2.

2016-11-29 21:42 UTC, closed without merging